services:
  db:
    image: postgres:18
    container_name: my-postgres
    environment:
      POSTGRES_USER: cognitoruser
      POSTGRES_PASSWORD: cognitorpassword
      POSTGRES_DB: cognitor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
