from typing import Any
import numpy as np

class HNSW:
    efConstruction: int
    efSearch: int
    def nb_neighbors(self, level: int) -> int: ...

class IndexHNSWFlat:
    hnsw: HNSW
    ntotal: int
    def __init__(self, d: int, m: int) -> None: ...

class IndexIDMap:
    index: Any
    ntotal: int
    def __init__(self, index: Any) -> None: ...
    def add_with_ids(self, x: np.ndarray, ids: np.ndarray) -> None: ...
    def search(self, x: np.ndarray, k: int) -> tuple[np.ndarray, np.ndarray]: ...

def downcast_index(index: Any) -> IndexHNSWFlat: ...
def write_index(index: IndexIDMap, fname: str) -> None: ...
def read_index(fname: str) -> IndexIDMap: ...
